# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./aa
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: aa/Dockerfile
          path: Dockerfile

      - name: Build Docker image
        run: docker build -t commit .

      - name: Test
        run: npm test

      - name: Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_REGISTRY }}:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f aa/Manifests/deployment.yaml -f aa/Manifests/service.yaml
