# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./aa
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: minikube 

      - name: Deploy pods
        run: kubectl apply -f Manifests/deployment.yaml -f Manifests/service.yaml --kubeconfig=${{ secrets.KUBE_CONFIG }}

      - name: Get pods
        run: kubectl get pods --kubeconfig=${{ secrets.KUBE_CONFIG }}
        

      - name: Test service URLs
        run: |
          minikube service list
          minikube service webapp-service --url   
        
      
          


       


