# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./aa
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      
      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: Rockstar108/react_test
          token: ${{ secrets.DOCKER_TOKEN }}
          path: aa/Dockerfile
          ref: main
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
            docker build -t rockstar24/sample_react_repo .
            docker push rockstar24/sample_react_repo:latest

      - name: Test
        run: npm test

     
      - name: Deploy to Kubernetes
        run: kubectl apply -f aa/Manifests/deployment.yaml -f aa/Manifests/service.yaml
